services:
  redis:
    image: registry.cn-beijing.aliyuncs.com/daodao-bot/redis:8.2.0
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M
    ports:
      - "6379:6379"
    volumes:
      - data-redis:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      TZ: Asia/Shanghai
      DT: "2025-01-01T00:00:00"
      REDIS_PASSWORD: redis
    #env_file:
    #  - .env
    networks:
      - zero
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]

networks:
  zero:
    external: true

volumes:
  data-redis:
    external: true
