spring:
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://mysql:3306/zero_tiny}
    username: ${MYSQL_USERNAME:zero}
    password: ${MYSQL_PASSWORD:zero}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 4
      maximum-pool-size: 16
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 120000
      connectionTimeout: 30000
