services:
  zero-server:
    image: crpi-lqf79pij6cz4kaey.cn-beijing.personal.cr.aliyuncs.com/ice-run-open/zero-server:tiny-latest
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    volumes:
      - logs:/logs/zero-server
    environment:
      TZ: Asia/Shanghai
      DT: "2025-01-01T00:00:00"
    env_file:
      - ../.env
      - .env
    labels:
      namespace: zero
      application: zero-server
      framework: spring-boot
    networks:
      - zero
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/actuator/health"]

networks:
  zero:
    external: true

volumes:
  logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /logs/zero-server

