services:
  zero-admin:
    image: crpi-lqf79pij6cz4kaey.cn-beijing.personal.cr.aliyuncs.com/ice-run-open/zero-admin:tiny-latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Shanghai
      DT: "2025-01-01T00:00:00"
    env_file:
      - ../.env
      - .env
    labels:
      namespace: zero
      application: zero-admin
    networks:
      - zero
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

networks:
  zero:
    external: true
