name: ${APPLICATION}

services:
  zero-admin:
    container_name: ${APPLICATION}
    image: ${DOCKER_REGISTRY}/${REGISTRY_NAMESPACE}/${APPLICATION}:${IMAGE_TAG}
    pull_policy: always
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
        reservations:
          cpus: "0.1"
          memory: 64M
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    environment:
      TZ: Asia/Shanghai
      DT: "2025-01-01T00:00:00"
    env_file:
      - ../.env
      - .env
    labels:
      namespace: ${NAMESPACE}
      application: ${APPLICATION}
    networks:
      - ${NETWORK}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

networks:
  zero:
    external: true
