services:
  mysql:
    image: registry.cn-beijing.aliyuncs.com/daodao-bot/mysql:9.4.0
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.2"
          memory: 256M
    ports:
      - "3306:3306"
    volumes:
      - data-mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      TZ: Asia/Shanghai
      DT: "2025-01-01T00:00:00.000"
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    networks:
      - zero
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

networks:
  zero:
    external: true

volumes:
  data-mysql:
    external: true
